config/routes.rb
Rails.application.routes.draw do
  get '/' => 'sites#home'
  post '/' => 'sites#index'

  resources :concerts do
  	resources :comments
  end

  get '/popular_concerts' => 'concerts#show_most_popular'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :concert
	validates :content, presence: true
end

app/models/concert.rb
class Concert < ActiveRecord::Base

	has_many :comments

	validates :band, presence: true, format: {with: /\A[a-zA-Z0-9\s]+\z/}
	validates :venue, presence: true, format: {with: /\A[a-zA-Z0-9\s]+\z/}
	validates :city, presence: true, format: {with: /\A[a-zA-Z\s]+\z/}
	validates :date, presence: true
	validates :price, presence: true, numericality: true, inclusion: {in: 0..99999}
	validates :description, presence: true

	def self.what_is_happening_today
		self.where("date=?", Date.today)
	end

	def self.what_is_happening_last_month
		date_start = Date.new(Date.today.year, Date.today.month,1)
		date_end = date_start.next_month.prev_day + 1.day
		self.where("date>?", date_start).where("date<?", date_end)
	end

	def self.are_you_cheaper_than(price)
		self.where("price<?",price).where("date>?", Date.today)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def new
		@concert = Comment.find params[:concert_id]
		@comments = @concert.comments.order("date ASC")
	end

	def new
		@concert = Comment.find params[:concert_id]
		@comments = @concert.comments.order("date ASC")
	end

	def create
		@concert = Concert.find params[:concert_id]
		@comments = @concert.comments.new(entry_params)
		if @comments.save
			redirect_to concert_comment_path(@concert,@comments)
		else
			render 'new'
		end
	end

	def show
		@concerts = Concert.find params[:concert_id]
		@comments = @concerts.comments.order("date ASC")
	end

	def index
		@concerts = Concert.find params[:concert_id]
		@comments = @concerts.comments.order("date ASC")
	end

	private
	def entry_params
		params.require(:comment).permit(:content)
	end
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController

	def index
		@concerts = Concert.all.what_is_happening_today
		@concerts_last_mont = Concert.all.what_is_happening_last_month
	end

	def new
		@concert = Concert.new
	end

	def create
		@concert = Concert.new(entry_params)
		if @concert.save
			redirect_to concert_path(@concert)
		else
			render 'new'
		end
	end

	def show
		@comment = Comment.new
		render ('concert_not_found') unless (@concert = Concert.find_by id: params[:id])

	end

	def show_most_popular
		
		@concerts = Concert.all.where("date>?", Date.today)
		ids = []
		how_many_comments_concerts = []
		@concerts.each do |concert|
			binding.pry
			how_many_comments = concert.comments.length
			concert.comments.each do |comment_id|
				ids << comment_id.id
			end
		end
		@comments = @concerts.comments
	end

	private
	def entry_params
		params.require(:concert).permit(:band,:venue,:city,:date,:price,:description)
	end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
	def home
	end
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/comments/index.html.erb
<%= @concert.band %>

<% @comments.each do |comment| %>
	<%= comment.content %>
<% end %>

app/views/comments/new.html.erb
<%= @concert.band %>

app/views/comments/show.html.erb
<div class="clearfix">
	<p> Comentarios sobre el concierto de <strong><%= @concerts.band %></strong> en <strong><%= @concerts.venue%></strong></p>
<% @concerts.comments.each do |comment| %>
	<div class="comment">
		<%= comment.content %>
	</div>
<% end %>
</div>

app/views/concerts/concert_not_found.html.erb
<div class="form">
<p> Concert with id <%= params[:id]%> not found</p>
</div>

app/views/concerts/index.html.erb
<div class="clearfix">
<section class="my_section">
	<h1> <strong> What is happening today...</strong></h1>
	<ul>
		<% @concerts.each do |c| %>
			<li>
				<strong> Band: </strong><%= c.band %>, <strong> Venue: </strong><%= c.venue %>, <strong> City: </strong><%= c.city %>,
				<strong> Date: </strong><%= c.date.strftime("%d-%m-%Y") %>
				<p> <strong> Description: </strong><%= c.description %> </p>
			</li>
		<% end %>
	</ul>
</section>

<aside class="my_aside">
	<p> <h3> <strong> Later this month... </strong></h3> </p>
	<ul>
		<% @concerts_last_mont.each do |c| %>
			<li>
				<strong> <%= link_to c.band, concert_path(c)%> </strong>
			</li>
		<% end %>
	</ul>

</aside>

</div>

app/views/concerts/new.html.erb
<% if @concert.errors.any? %>
	<ul>
		<% @concert.errors.full_messages.each do |error| %>
			<li> <%= error %> </li>
		<% end %>
	</ul>
<% end %>


<div class="form">

	<%= form_for @concert do |f| %>

		<%= f.label  :band %>
		<%= f.text_field :band %>

		<%= f.label  :venue %>
		<%= f.text_field :venue %>

		<%= f.label  :city %>
		<%= f.text_field :city %>

		<%= f.label  :date %>
		<%= f.date_field :date , class: "date"%>

		<%= f.label  :price %>
		<%= f.number_field :price %>

		<%= f.label  :description %>
		<%= f.text_area :description, rows: 3, cols: 40 %>

		<p> <%= f.submit 'Create concert'%> </p>


	<% end %>

</div>

app/views/concerts/show.html.erb
<div class="clearfix">
	<p> <strong> Concert: </strong>  </p>
	<ul>
		<li> <strong> Band: </strong><%= @concert.band %> </li>
		<li> <strong> Venue: </strong><%= @concert.venue %> </li>
		<li> <strong> City: </strong><%= @concert.city %> </li>
		<li> <strong> Date: </strong><%= @concert.date %> </li>
		<li> <strong> Price: </strong><%= @concert.price %> </li>
		<li> <strong> Description: </strong><%= @concert.description %> </li>
	</ul>
</div>

<div class="clearfix">
	<p> Comentarios sobre el concierto de <strong><%= @concert.band %></strong> en <strong><%= @concert.venue%></strong></p>
	<% @concert.comments.each do |comment| %>
		<div class="comment">
			<%= comment.content %>
		</div>
	<% end %>	
</div>

<div class="clearfix">
	<%= form_for [@concert, @comment] do |f| %>

		<%= f.label  "Add a comment" %>
		<%= f.text_area :content, rows: 3, cols: 95 %>

		<p> <%= f.submit 'Add a comment'%> </p>

	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicConcertNetwork</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Raleway:900,400,200' rel='stylesheet' type='text/css'>

  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		
		<div class="header">
			Welcome to this Music Concert Network	
		</div>

			<%= yield %>
		
	</div>
	<div class="footer">
			2015 © Ironhack powered
	</div>
</body>
</html>

app/views/sites/home.html.erb
<div class="clearfix">
<p> <%= link_to "Add a new concert", new_concert_path %> </p>
	<%= form_tag do |f| %>
		  <%= label_tag(:money, "Introduce how much are you willing to spend...") %>
		  <%= number_field_tag(:money) %>
		  <%= submit_tag("Search Concerts!!") %>
	<% end %>
</div>

app/views/sites/index.html.erb
<div class="clearfix">
<h3> <strong> Concerts you can buy with <%=params[:money]%>€</strong> </h3>
	<ul>	
		<% Concert.all.are_you_cheaper_than(params[:money].to_f).each do |concert|%>
		<li>
			<%= concert.band %> - <%= concert.price %>€ - <%= concert.date.strftime("%d-%m-%Y") %>
		</li>
		<% end %>	
	</ul>
</div>